name: twitter_oauth2_pkce
description: Provides the optimized and easiest way to integrate OAuth 2.0 PKCE with Twitter API in Flutter.
version: 1.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  crypto: ^3.0.6
  flutter_web_auth_2: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  import_sorter: ^4.6.0
  test: ^1.22.0
